### ISSUE TITLE
EPIC: doc for phase-3

### ISSUE THREAD

**Issue by SebastianElvis** [babylonlabs-io/babylonlabs.github.io#16]
- [ ] Migrate Notion site to Github
- [ ] Landing page that clarifies the concepts and directs readers to different integration docs
- [ ] Information page that provides devnet endpoints, faucet information, etc..
- [ ] Doc for OP stack / Arbitrum Orbit integrations
- [ ] Split the doc for integrating with Euphrates into 3 pages (for BSN, for FP, for staker)
